MVC Online Bookshop/Areas/Admin/Controllers/FrontPageController.cs
using Bookshop.DataAccess.Repository.IRepository;
using Bookshop.Models;
using Bookshop.Models.ViewModels;
using Bookshop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp.Formats.Jpeg;

namespace MVC_Online_Bookshop.Areas.Admin.Controllers
{
    [Area(SD.RoleAdmin)]
    [Authorize(Roles = $"{SD.RoleAdmin}, {SD.RoleEmployee}")]
    public class FrontPageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private IWebHostEnvironment appEnvironment { get; }
        public FrontPageController(IUnitOfWork unitOfWork, IWebHostEnvironment appEnvironment)
        {
            this._unitOfWork = unitOfWork;
            this.appEnvironment = appEnvironment;
        }

        //INDEX
        public async Task<IActionResult> Index()
        {
            var vm = new FrontPageManageVM();
            var carouselsDb = _unitOfWork.CarouselRepository.GetAll().Include(x => x.Category).OrderBy(x => x.DisplayOrder);
            var headersDb = await _unitOfWork.HeaderRepository.GetAll().ToListAsync();
            vm.Carousels = await carouselsDb.ToListAsync();
            vm.Headers = headersDb;
            return View(vm);
        }


        // HEADER OPERATIONS
        public async Task<IActionResult> HeaderUpsert(int? id, Uri? returnUri)
        {
            returnUri ??= HttpContext.Request.GetTypedHeaders().Referer;
            ViewData["ReturnUri"] = returnUri;
            if (id is null or 0)
            {
                return View(new Header());
            }

            var headerDb = await _unitOfWork.HeaderRepository.Get(x => x.Id == id);

            return View(headerDb);
        }

        [HttpPost]
        public async Task<IActionResult> HeaderUpsert(Header header, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Model state is invalid.";
                return View(header);
            }
            if (file is not null)
            {
                await SaveBookImage(header, file);
            }

            if (header.Id is 0)
            {
                _unitOfWork.HeaderRepository.Add(header);
                TempData["success"] = "Created Slide";
            }
            else
            {
                _unitOfWork.HeaderRepository.Update(header);
                TempData["success"] = "Updated Slide";
            }

            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));

        }

        private async Task SaveBookImage(Header header, IFormFile file)
        {
            string filename = header.ImagePath ?? @"Images\Slides\" + Guid.NewGuid().ToString() + ".jpg";
            string path = Path.Combine(appEnvironment.WebRootPath, filename);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                filename = @"Images\Product\" + Guid.NewGuid().ToString() + ".jpg";
                path = Path.Combine(appEnvironment.WebRootPath, filename);
            }

            using (var image = await Image.LoadAsync(file.OpenReadStream()))
            {
                if (image.Width != 2048 || image.Height != 600)
                {
                    image.Mutate(img => img.Resize(2048, 600, KnownResamplers.Lanczos3));
                }
                await image.SaveAsync(path, new JpegEncoder{Quality = 75});
            }

            header.ImagePath = filename;
        }

        public async Task<IActionResult> HeaderDelete(int? id, Uri? returnUri)
        {
            returnUri ??= HttpContext.Request.GetTypedHeaders().Referer;
            ViewData["ReturnUri"] = returnUri;

            if (id is null or 0)
            {
                return NotFound();
            }

            var headerDb = await _unitOfWork.HeaderRepository.Get(x => x.Id == id);
            return View(headerDb);
        }
        [HttpPost]
        public async Task<IActionResult> HeaderDelete(Header header)
        {
            if (header.Id is 0)
            {
                return NotFound();
            }

            if (header.ImagePath is not null)
            {
                string filename = header.ImagePath;
                string path = Path.Combine(appEnvironment.WebRootPath, filename);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);

                }
            }

            _unitOfWork.HeaderRepository.Delete(header);
            await _unitOfWork.SaveAsync();

            TempData["success"] = "Removed slide";
            return RedirectToAction(nameof(Index));
        }


        //CAROUSEL OPERATIONS
        public async Task<IActionResult> CarouselUpsert(int? id, Uri? returnUri)
        {
            returnUri ??= HttpContext.Request.GetTypedHeaders().Referer;
            ViewData["ReturnUri"] = returnUri;
            ViewData["CategoryItems"] = await _unitOfWork.CategoryRepository.GetAll().OrderBy(x => x.DisplayOrder).Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToListAsync();
            ViewData["SortItems"] = new List<SelectListItem>()
            {
                new() { Text = "Title", Value = "Title" },
                new () { Text = "Author", Value = "Author" },
                new () { Text = "Recent", Value = "Id" }
            };

            if (id is null) return View(new Carousel());

            var carouselDb = await _unitOfWork.CarouselRepository.Get(x => x.Id == id);
            return View(carouselDb);


        }

        [HttpPost]
        public async Task<IActionResult> CarouselUpsert(Carousel carousel, Uri? returnUri)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine, ModelState.Keys.Where(i => ModelState[i]?.Errors.Count > 0).Select(k =>
                    new KeyValuePair<string, string>(k, ModelState[k]!.Errors.First().ErrorMessage)));
                TempData["error"] = $"Model state is invalid. Error log: {errors}";
                return View(carousel);
            }

            if (carousel.Id is 0)
            {
                _unitOfWork.CarouselRepository.Add(carousel);
                TempData["success"] = "Created carousel";
            }

            else
            {
                _unitOfWork.CarouselRepository.Update(carousel);
                TempData["success"] = "Updated carousel";
            }

            await _unitOfWork.SaveAsync();


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CarouselDelete(int? id)
        {
            if (id is null) return NotFound();
            var returnUri = Url.Action(nameof(Index));
            ViewData["ReturnUri"] = returnUri;

            var carouselDb = await _unitOfWork.CarouselRepository.Get(x => x.Id == id);
            if (carouselDb is null) return NotFound();

            return View(carouselDb);
        }

        [HttpPost]
        public async Task<IActionResult> CarouselDelete(Carousel carousel)
        {
            if (carousel.Id is 0)
            {
                return NotFound();
            }

            _unitOfWork.CarouselRepository.Delete(carousel);
            await _unitOfWork.SaveAsync();

            TempData["success"] = "Removed carousel";
            return RedirectToAction(nameof(Index));
        }
    }
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/CarouselDelete.cshtml
@model Carousel
@{
    ViewData["Title"] = "Delete Carousel";
}

<div class="float-start mt-2 mb-4">
    @* Back Button *@
    <a class="btn btn-outline-danger btn-lg px-4" href="@ViewData["ReturnUri"]">Back</a>
</div>
<div class="container d-flex">
    <div class="card shadow border-0 mt-4 mb-5 col-9 offset-2">
        <div class="card-header">
            <div class="row text-center">
                <h2 class="text-danger">Delete Carousel</h2>
            </div>
        </div>
        <div class="card-body p-4">
            <form method="post" class="" asp-area="Admin" asp-controller="FrontPage" asp-action="CarouselDelete">
                <div class="form-floating vstack gap-3">
                    @*CATEGORY NAME*@
                    <div class="form-floating">
                        <input asp-for="Title" type="text" class="form-control" placeholder="Category Name" disabled="disabled"/>
                        <label asp-for="Title" class=""></label>
                    </div>

                    @*Tag*@
                    <div class="form-floating">
                        <select asp-for="CategoryId" class="form-select align-middle scrollable-select" id="floatingSelect2" disabled="disabled">
                            <option selected disabled>Select a tag</option>
                        </select>
                        <label for="floatingSelect2">Category/Tag</label>
                    </div>
                    @*SORT ORDER*@
                    <div class="form-floating">
                        <select asp-for="SortOrder" class="form-select align-middle" id="floatingSelect1" disabled="disabled">
                            <option selected disabled>@Model.SortOrder</option>
                        </select>
                        <label for="floatingSelect1">Sort Order</label>
                    </div>
                    @* DISPLAY ORDER *@
                    <div class="form-floating">
                        <input type="number" asp-for="DisplayOrder" class="form-control" placeholder="Order on Page" disabled="disabled"/>
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    @*SUBMIT*@
                    <div class="container">
                        <div class="row col-6 offset-3">
                            <div class="col-8 mx-auto">
                                <div id="confirmDeleteSpan" style="display:none" class="">
                                    <div class="row gap-1">
                                        <button type="submit" class="btn btn-danger form-control col">Yes</button>
                                        <a href="#!" class="btn btn-primary form-control col"
                                           onclick="confirmDelete(false)">No</a>
                                    </div>

                                    <p class="text-center mt-1 text-danger">Are you sure you want to delete?</p>
                                </div>
                                <div id="deleteSpan">
                                    <a type="button" href="#!" class="btn btn-danger form-control"
                                       onclick="confirmDelete(true)">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://cdn.tiny.cloud/1/2ewupqynbfix7nj1m6dcobl5ub0qcn03vjog34v5ofd7boug/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <partial name="_ConfirmDeleteScriptPartial"/>
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/CarouselUpsert.cshtml
@model Carousel
@{
    bool create = @Model.Id == 0;
}
@{
    ViewData["Title"] = $"{(create ? "Create" : "Update")} Carousel";
}

<div class="float-start mt-2 mb-4">
    @* Back Button *@
    <a class="btn btn-outline-danger btn-lg" href="@ViewData["ReturnUri"]">Back to Carousels</a>
</div>
<div class="container d-flex">
    <div class="card shadow border-0 mt-4 mb-5 col-9 offset-2">
        <div class="card-header">
            <div class="row col-12 text-center">
                <h2 class="text-primary">@(create ? "Create" : "Update") Category</h2>
            </div>
        </div>
        <div class="card-body p-4">
            <form method="post" class="" asp-area="Admin" asp-controller="FrontPage" asp-action="CarouselUpsert" asp-route-returnUri="@ViewData["ReturnUri"]">
                <div class="form-floating vstack gap-3">
                    @*CATEGORY NAME*@
                    <div class="form-floating">
                        <input asp-for="Title" type="text" class="form-control" placeholder="Category Name"/>
                        <label asp-for="Title" class=""></label>
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>

                    @*Tag*@
                    <div>
                        <label class="text-muted" asp-for="CategoryId" for="floatingSelect2">Category/Tag</label>
                        <select asp-for="CategoryId" asp-items="@((List<SelectListItem>)ViewData["CategoryItems"]!)" class="form-select align-middle" id="floatingSelect2">
                            <option selected disabled>Select a tag</option>
                        </select>
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                        
                    </div>
                    
                    @*SORT ORDER*@
                    <div>
                        <label class="text-muted" asp-for="SortOrder" for="floatingSelect1">Sort Order</label>
                        <select asp-for="SortOrder" asp-items="@((List<SelectListItem>)ViewData["SortItems"]!)" class="form-select align-middle" id="floatingSelect1">
                            <option selected disabled>Select a sort order</option>
                        </select>

                    </div>
                    @* DISPLAY ORDER *@
                    <div class="form-floating">
                        <input type="number" asp-for="DisplayOrder" class="form-control" placeholder="Order on Page"/>
                        <label asp-for="DisplayOrder"></label>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                    @*SUBMIT / BACK*@
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary form-control">@(create ? "Create" : "Update")</button>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>





@section Scripts {
    @{
        <script src="https://cdn.tiny.cloud/1/2ewupqynbfix7nj1m6dcobl5ub0qcn03vjog34v5ofd7boug/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <partial name="_ValidationScriptsPartial" />

        <script type="text/javascript">

            $('.form-select').select2(
                {
                    theme: 'bootstrap-5',
                    width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
                    placeholder: $(this).data('placeholder'),
                    closeOnSelect: true,
                    allowClear: false,
                });

        </script>
    }
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/Delete.cshtml
@model Carousel
@{
    ViewData["Title"] = "Delete Carousel";
}

<div class="float-start mt-2 mb-4">
    @* Back Button *@
    <a class="btn btn-outline-danger btn-lg px-4" href="@ViewData["ReturnUri"]">Back</a>
</div>
<div class="container d-flex">
    <div class="card shadow border-0 mt-4 mb-5 col-9 offset-2">
        <div class="card-header">
            <div class="row text-center">
                <h2 class="text-danger">Delete Carousel</h2>
            </div>
        </div>
        <div class="card-body p-4">
            <form method="post" class="" asp-area="Admin" asp-controller="FrontPage" asp-action="Delete">
                <div class="form-floating vstack gap-3">
                    @*CATEGORY NAME*@
                    <div class="form-floating">
                        <input asp-for="Title" type="text" class="form-control" placeholder="Category Name" disabled="disabled"/>
                        <label asp-for="Title" class=""></label>
                    </div>

                    @*Tag*@
                    <div class="form-floating">
                        <select asp-for="CategoryId" class="form-select align-middle scrollable-select" id="floatingSelect2" disabled="disabled">
                            <option selected disabled>Select a tag</option>
                        </select>
                        <label for="floatingSelect2">Category/Tag</label>
                    </div>
                    @*SORT ORDER*@
                    <div class="form-floating">
                        <select asp-for="SortOrder" class="form-select align-middle" id="floatingSelect1" disabled="disabled">
                            <option selected disabled>@Model.SortOrder</option>
                        </select>
                        <label for="floatingSelect1">Sort Order</label>
                    </div>
                    @* DISPLAY ORDER *@
                    <div class="form-floating">
                        <input type="number" asp-for="DisplayOrder" class="form-control" placeholder="Order on Page" disabled="disabled"/>
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    @*SUBMIT*@
                    <div class="container">
                        <div class="row col-6 offset-3">
                            <div class="col-8 mx-auto">
                                <div id="confirmDeleteSpan" style="display:none" class="">
                                    <div class="row gap-1">
                                        <button type="submit" class="btn btn-danger form-control col">Yes</button>
                                        <a href="#!" class="btn btn-primary form-control col"
                                           onclick="confirmDelete(false)">No</a>
                                    </div>

                                    <p class="text-center mt-1 text-danger">Are you sure you want to delete?</p>
                                </div>
                                <div id="deleteSpan">
                                    <a type="button" href="#!" class="btn btn-danger form-control"
                                       onclick="confirmDelete(true)">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    <partial name="_ConfirmDeleteScriptPartial"/>
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/HeaderDelete.cshtml
@model Header
@{
}
@{
    ViewData["Title"] = "Remove Slide";
}

<div class="float-start mt-2 mb-4">
    @* Back Button *@
    <a class="btn btn-outline-danger btn-lg p-3" href="@ViewData["ReturnUri"]">Back</a>
</div>
<div class="container d-flex">
    <div class="card shadow border-0 mt-4 mb-5 col-9 offset-2">
        <div class="card-header">
            <div class="row col-12 text-center">
                <h2 class="text-danger">Delete Slide</h2>
            </div>
        </div>
        <div class="card-body p-4">
            <form method="post" class="" asp-area="Admin" asp-controller="FrontPage" asp-action="HeaderDelete">
                <input asp-for="Id" hidden/>
                <input asp-for="ImagePath" hidden/>
                <div class="form-floating vstack gap-3">
                    @*SLIDE NAME*@
                    <div class="form-floating">
                        <input asp-for="Name" type="text" class="form-control" placeholder="Slide Name" disabled="disabled"/>
                        <label asp-for="Name" class=""></label>
                    </div>
                    @*ALT TEXT*@
                    <div class="form-floating">
                        <input asp-for="AltText" type="text" class="form-control" placeholder="Alt Text" disabled="disabled"/>
                        <label asp-for="AltText" class=""></label>
                    </div>

                    @*LINK*@
                    <div class="form-floating">
                        <input asp-for="LinkPath" type="text" class="form-control" placeholder="Link (optional)" disabled="disabled"/>
                        <label asp-for="LinkPath" class=""></label>
                    </div>

                    @*Image*@
                    <div class="mt-2 mb-3 col-sm-12 col-md-12">
                        <label asp-for="ImagePath" class="pe-3 pt-2 bg-opacity-10 form-text text-muted">@Model.ImagePath</label>
                        <input name="file" type="file" accept="image/*" class="form-control" placeholder="Cover Art" disabled="disabled"/>
                    </div>

                    @* DISPLAY ORDER *@
                    <div class="form-floating">
                        <input type="number" asp-for="DisplayOrder" class="form-control" placeholder="Order in Slideshow" disabled="disabled"/>
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    @*SUBMIT*@
                    <div class="container">
                        <div class="row col-6 offset-3">
                            <div class="col-8 mx-auto">
                                <div id="confirmDeleteSpan" style="display:none" class="">
                                    <div class="row gap-1">
                                        <button type="submit" class="btn btn-danger form-control col">Yes</button>
                                        <a href="#!" class="btn btn-primary form-control col"
                                           onclick="confirmDelete(false)">No</a>
                                    </div>

                                    <p class="text-center mt-1 text-danger">Are you sure you want to delete?</p>
                                </div>
                                <div id="deleteSpan">
                                    <a type="button" href="#!" class="btn btn-danger form-control"
                                       onclick="confirmDelete(true)">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>





@section Scripts {
    @{
        <script src="https://cdn.tiny.cloud/1/2ewupqynbfix7nj1m6dcobl5ub0qcn03vjog34v5ofd7boug/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <partial name="_ConfirmDeleteScriptPartial"/>
    }
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/HeaderUpsert.cshtml
@model Header
@{
    bool create = @Model.Id == 0;
}
@{
    ViewData["Title"] = $"{(create ? "Create" : "Update")} Slide";
}

<div class="float-start mt-2 mb-4">
    @* Back Button *@
    <a class="btn btn-outline-danger btn-lg px-3" href="@ViewData["ReturnUri"]">Back</a>
</div>
<div class="container d-flex">
    <div class="card shadow border-0 mt-4 mb-5 col-9 offset-2">
        <div class="card-header">
            <div class="row col-12 text-center">
                <h2 class="text-primary">@(create ? "Create" : "Update") Slide</h2>
            </div>
        </div>
        <div class="card-body p-4">
            <form method="post" class="" asp-area="Admin" asp-controller="FrontPage" asp-action="HeaderUpsert" enctype="multipart/form-data">
                <input asp-for="Id" hidden />
                <input asp-for="ImagePath" hidden />
                <div class="form-floating vstack gap-3">
                    @*SLIDE NAME*@
                    <div class="form-floating">
                        <input asp-for="Name" type="text" class="form-control" placeholder="Slide Name"/>
                        <label asp-for="Name" class=""></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    @*ALT TEXT*@
                    <div class="form-floating">
                        <input asp-for="AltText" type="text" class="form-control" placeholder="Alt Text"/>
                        <label asp-for="AltText" class=""></label>
                        <span asp-validation-for="AltText" class="text-danger"></span>
                    </div>

                    @*LINK*@
                    <div class="form-floating">
                        <input asp-for="LinkPath" type="text" class="form-control" placeholder="Link (optional)"/>
                        <label asp-for="LinkPath" class=""></label>
                        <span asp-validation-for="LinkPath" class="text-danger"></span>
                    </div>

                    @*Image*@
                    <div class="mt-2 mb-3 col-sm-12 col-md-12">
                        <label asp-for="ImagePath" class="pe-3 pt-2 bg-opacity-10 form-text text-warning">Image must be 2048 x 600 or it will be resized</label>
                        <input name="file" type="file" accept="image/*" class="form-control" placeholder="Slide Image"/>
                    </div>

                    @* DISPLAY ORDER *@
                    <div class="form-floating">
                        <input type="number" asp-for="DisplayOrder" class="form-control" placeholder="Order in Slideshow"/>
                        <label asp-for="DisplayOrder"></label>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                    @*SUBMIT / BACK*@
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary form-control">@(create ? "Create" : "Update")</button>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>





@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
        <script src="https://cdn.tiny.cloud/1/2ewupqynbfix7nj1m6dcobl5ub0qcn03vjog34v5ofd7boug/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <script type="text/javascript">

            $('.form-select').select2(
                {
                    theme: 'bootstrap-5',
                    width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
                    placeholder: $(this).data('placeholder'),
                    closeOnSelect: true,
                    allowClear: false,
                });

        </script>
    }
}

MVC Online Bookshop/Areas/Admin/Views/FrontPage/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Bookshop.DataAccess.Repository
@model FrontPageManageVM
@{
    ViewData["Title"] = "Front Page Management";
    int? currentPageSize = (int?)ViewData["CurrentPageSize"];
}

<div class="card shadow mt-4 mb-4">
    <div class="row py-2 m-0 card-header border-0 shadow-none">
        <div class="col-6">
            <h2 class="text-primary">Header Slides</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="FrontPage" asp-action="HeaderUpsert" class="btn btn-primary"><i class="bi bi-plus-circle-fill"></i> Slide</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered table-striped w-100 ">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Image</th>
                <th>Links to</th>
                <th>Display Order</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var slide in Model.Headers)
            {
                <tr>
                    <td>@slide.Name</td>
                    <td>@slide.AltText</td>
                        <td><a href="~/@slide.ImagePath" target="_blank" rel="noreferrer noopener">Image</a></td>
                    <td><a href="@slide.LinkPath" target="_blank" rel="noreferrer noopener">Links to</a></td>
                    <td>@slide.DisplayOrder</td>
                    <td class="text-sm-center">
                        <div class=" w-75 btn-group" role="group">
                            <a asp-controller="FrontPage" asp-action="HeaderUpsert" asp-route-id="@slide.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-fill"></i> Edit</a>
                            <a asp-controller="FrontPage" asp-action="HeaderDelete" asp-route-id="@slide.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>

    </div>

</div>


<div class="card shadow mt-4 mb-4">
    <div class="row py-2 m-0 card-header border-0 shadow-none">
        <div class="col-6">
            <h2 class="text-primary">Carousels</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="FrontPage" asp-action="CarouselUpsert" class="btn btn-primary"><i class="bi bi-plus-circle-fill"></i> Carousel</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered table-striped w-100 ">
            <thead>
            <tr>
                <th>Title</th>
                <th>Category/Tag</th>
                <th>Sort Order</th>
                <th>Display Order</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var carousel in Model.Carousels)
            {
                <tr>
                    <td>@carousel.Title</td>
                    <td>@carousel.Category.Name</td>
                    <td>@carousel.SortOrder</td>
                    <td>@carousel.DisplayOrder</td>
                    <td class="text-sm-center">
                        <div class=" w-75 btn-group" role="group">
                            <a asp-controller="FrontPage" asp-action="CarouselUpsert" asp-route-id="@carousel.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-fill"></i> Edit</a>
                            <a asp-controller="FrontPage" asp-action="CarouselDelete" asp-route-id="@carousel.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>

    </div>

</div>